from __future__ import annotations

SHADOWBROKER_SOURCE_CATALOG = [
    {
        "source": "OpenSky Network",
        "domain": "opensky-network.org",
        "category": "Aviation",
        "usage": "Commercial and private flight telemetry",
        "update_frequency": "~60s",
        "api_key_required": "Optional",
    },
    {
        "source": "adsb.lol",
        "domain": "adsb.lol",
        "category": "Aviation",
        "usage": "Military aircraft telemetry",
        "update_frequency": "~60s",
        "api_key_required": "No",
    },
    {
        "source": "aisstream.io",
        "domain": "aisstream.io",
        "category": "Maritime",
        "usage": "Real-time vessel positions via WebSocket",
        "update_frequency": "Real-time",
        "api_key_required": "Yes",
    },
    {
        "source": "CelesTrak",
        "domain": "celestrak.org",
        "category": "Space",
        "usage": "Satellite positions using TLE + SGP4",
        "update_frequency": "~60s",
        "api_key_required": "No",
    },
    {
        "source": "USGS Earthquake",
        "domain": "earthquake.usgs.gov",
        "category": "Earth observation",
        "usage": "Global seismic events",
        "update_frequency": "~60s",
        "api_key_required": "No",
    },
    {
        "source": "GDELT",
        "domain": "gdeltproject.org",
        "category": "Geopolitics",
        "usage": "Conflict and event monitoring",
        "update_frequency": "Periodic",
        "api_key_required": "No",
    },
    {
        "source": "SatNOGS",
        "domain": "satnogs.org",
        "category": "Signals",
        "usage": "Amateur satellite ground station activity",
        "update_frequency": "~30min",
        "api_key_required": "No",
    },
    {
        "source": "TinyGS",
        "domain": "tinygs.com",
        "category": "Signals",
        "usage": "LoRa satellite ground stations",
        "update_frequency": "~30min",
        "api_key_required": "No",
    },
    {
        "source": "Meshtastic MQTT",
        "domain": "meshtastic.org",
        "category": "Signals",
        "usage": "Mesh radio node positions",
        "update_frequency": "Real-time",
        "api_key_required": "No",
    },
]
